name: Pytesting & Pylinting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validation:
  
    name: Pytesting & Pylinting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        
    - name: Install libraries
      run: pip install -r ./requirements.txt

    - name: Install libraries
      run: pip install -r ./pipeline/pipeline_requirements.txt
      
    - name: Install pipeline reqs
      run: pip install -r ./pipeline/pipeline_requirements.txt
      
    - name: Linting
      run: pylint *.py --fail-under 8
      
    - name: Testing
      run: pytest .

